import { Phone, MapPin, MessageCircle, Instagram, Facebook } from 'lucide-react';
import { ScrollReveal } from '@/components/ScrollReveal';
import { SITE_PHONE_DISPLAY, SITE_PHONE_RAW, SITE_INSTAGRAM, SITE_FACEBOOK, SITE_CITY } from '@/lib/site-config';

export default function Contact() {
  const whatsappMessage = encodeURIComponent('Olá! Gostaria de mais informações.');
  return (
    <div className="py-8 md:py-12"><div className="container max-w-5xl"><ScrollReveal><div className="text-center mb-10"><h1 className="font-display text-3xl md:text-4xl font-light mb-2">Contato</h1><p className="text-sm text-muted-foreground font-body">Fale com a nossa equipe pelos canais abaixo.</p></div></ScrollReveal><div className="grid md:grid-cols-2 gap-6"><ScrollReveal><a href={`https://wa.me/${SITE_PHONE_RAW}?text=${whatsappMessage}`} target="_blank" rel="noreferrer" className="block rounded-3xl border border-border p-6 bg-cream/40 hover:border-gold transition-colors"><div className="flex items-start gap-4"><div className="w-12 h-12 bg-background rounded-full flex items-center justify-center"><MessageCircle className="w-5 h-5 text-gold" /></div><div><h2 className="font-display text-2xl font-light">WhatsApp</h2><p className="text-sm text-muted-foreground font-body mt-2">Atendimento rápido para dúvidas, compras e suporte.</p><p className="text-lg font-body font-semibold mt-4">{SITE_PHONE_DISPLAY}</p></div></div></a></ScrollReveal><ScrollReveal delay={0.05}><div className="rounded-3xl border border-border p-6 bg-background"><div className="space-y-5 text-sm font-body"><div className="flex items-start gap-3"><Phone className="w-5 h-5 text-gold mt-0.5" /><div><p className="font-semibold">Telefone / WhatsApp</p><p className="text-muted-foreground">{SITE_PHONE_DISPLAY}</p></div></div><div className="flex items-start gap-3"><MapPin className="w-5 h-5 text-gold mt-0.5" /><div><p className="font-semibold">Localização</p><p className="text-muted-foreground">{SITE_CITY}</p></div></div><a href={SITE_INSTAGRAM} target="_blank" rel="noreferrer" className="flex items-start gap-3 hover:text-gold transition-colors"><Instagram className="w-5 h-5 mt-0.5" /><div><p className="font-semibold">Instagram</p><p className="text-muted-foreground">@autentica_fashionof</p></div></a><a href={SITE_FACEBOOK} target="_blank" rel="noreferrer" className="flex items-start gap-3 hover:text-gold transition-colors"><Facebook className="w-5 h-5 mt-0.5" /><div><p className="font-semibold">Facebook</p><p className="text-muted-foreground">Abrir página oficial</p></div></a></div></div></ScrollReveal></div></div></div>
  );
}
