import { Link } from 'react-router-dom';
import { Instagram, Phone, MapPin, Facebook } from 'lucide-react';
import { SITE_INSTAGRAM, SITE_FACEBOOK, SITE_PHONE_DISPLAY, SITE_CITY } from '@/lib/site-config';

export function Footer() {
  return (
    <footer className="bg-primary text-primary-foreground"><div className="container py-16"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12"><div><h3 className="font-display text-2xl font-semibold mb-4">AUTÊNTICA <span className="font-light">FASHION</span><span className="text-gold">F</span></h3><p className="text-sm text-primary-foreground/60 font-body leading-relaxed">Moda com estilo, praticidade e atendimento direto para suas clientes.</p><div className="flex gap-3 mt-6"><a href={SITE_INSTAGRAM} target="_blank" rel="noreferrer" className="w-9 h-9 rounded-full border border-primary-foreground/20 flex items-center justify-center hover:bg-primary-foreground/10 transition-colors" aria-label="Instagram"><Instagram className="w-4 h-4" /></a><a href={SITE_FACEBOOK} target="_blank" rel="noreferrer" className="w-9 h-9 rounded-full border border-primary-foreground/20 flex items-center justify-center hover:bg-primary-foreground/10 transition-colors" aria-label="Facebook"><Facebook className="w-4 h-4" /></a></div></div><div><h4 className="text-xs tracking-luxury uppercase font-body font-semibold mb-6">Institucional</h4><nav className="flex flex-col gap-3">{[{ label: 'Sobre a Marca', to: '/sobre' },{ label: 'Contato', to: '/contato' },{ label: 'Revenda', to: '/revenda' },{ label: 'Trocas e Devoluções', to: '/trocas' },{ label: 'Política de Privacidade', to: '/privacidade' },{ label: 'Termos de Uso', to: '/termos' }].map(link => <Link key={link.to} to={link.to} className="text-sm text-primary-foreground/60 hover:text-primary-foreground transition-colors font-body">{link.label}</Link>)}</nav></div><div><h4 className="text-xs tracking-luxury uppercase font-body font-semibold mb-6">Ajuda</h4><nav className="flex flex-col gap-3">{[{ label: 'Minha Conta', to: '/conta' },{ label: 'Meus Pedidos', to: '/pedidos' },{ label: 'Favoritos', to: '/favoritos' }].map(link => <Link key={link.to} to={link.to} className="text-sm text-primary-foreground/60 hover:text-primary-foreground transition-colors font-body">{link.label}</Link>)}</nav></div><div><h4 className="text-xs tracking-luxury uppercase font-body font-semibold mb-6">Contato</h4><div className="flex flex-col gap-4 text-sm text-primary-foreground/60 font-body"><div className="flex items-start gap-3"><Phone className="w-4 h-4 mt-0.5 flex-shrink-0" /><span>{SITE_PHONE_DISPLAY}</span></div><div className="flex items-start gap-3"><MapPin className="w-4 h-4 mt-0.5 flex-shrink-0" /><span>{SITE_CITY}</span></div></div></div></div><div className="border-t border-primary-foreground/10 mt-12 pt-8 text-center"><p className="text-xs text-primary-foreground/40 font-body">© 2026 Autêntica FashionF. Todos os direitos reservados.</p></div></div></footer>
  );
}
